In [ ]:
!pip install -q ucimlrepo

In [ ]:
!pip -q install ucimlrepo

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from ucimlrepo import fetch_ucirepo

student_performance = fetch_ucirepo(id=320)

X_original = student_performance.data.features
y_original = student_performance.data.targets

df = pd.concat(
    [X_original, y_original],
    axis=1
)

print("DATASET LOADED SUCCESSFULLY")
print("=" * 60)

print("\nDATASET SHAPE")
print(df.shape)

print("\nCOLUMN NAMES")
print(df.columns.tolist())

print("\nFIRST 5 ROWS")
display(df.head())

print("\nLAST 5 ROWS")
display(df.tail())

print("\nDATA TYPES")
print(df.dtypes)

print("\nDATASET INFORMATION")
df.info()

print("\nMISSING VALUES")
missing_values = df.isnull().sum()
display(missing_values)

print("Total Missing Values:", df.isnull().sum().sum())

print("\nDUPLICATE VALUES")
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicate rows removed.")
else:
    print("No duplicate rows found.")

print("\nNUMERICAL VARIABLES")
numerical_columns = df.select_dtypes(
    include=np.number
).columns.tolist()
print(numerical_columns)

print("\nCATEGORICAL VARIABLES")
categorical_columns = df.select_dtypes(
    exclude=np.number
).columns.tolist()
print(categorical_columns)

print("\nDATASET SLICING")

print("\nFirst 10 rows:")
display(df.iloc[:10])

print("\nSelected columns:")
display(
    df[
        [
            "age",
            "studytime",
            "failures",
            "absences",
            "G1",
            "G2",
            "G3"
        ]
    ].head()
)

print("\nStudents with G3 >= 15")

high_performers = df[df["G3"] >= 15]

print("Number of high performers:", len(high_performers))

display(high_performers.head())

print("\nBINARY ENCODING")

df_encoded = df.copy()

binary_mapping = {
    "yes": 1,
    "no": 0,
    "F": 0,
    "M": 1
}

for col in df_encoded.columns:

    if df_encoded[col].dtype == "object":

        unique_values = set(
            df_encoded[col].dropna().unique()
        )

        if unique_values.issubset(
            set(binary_mapping.keys())
        ):

            df_encoded[col] = (
                df_encoded[col].map(binary_mapping)
            )

print("Binary encoded dataset:")
display(df_encoded.head())

print("\nONE-HOT ENCODING")

categorical_for_encoding = (
    df.select_dtypes(
        exclude=np.number
    ).columns.tolist()
)

df_onehot = pd.get_dummies(
    df,
    columns=categorical_for_encoding,
    drop_first=True
)

print("Original shape:", df.shape)
print("Encoded shape:", df_onehot.shape)

display(df_onehot.head())

print("\nDATA TRANSFORMATION")

df_transformed = df.copy()

df_transformed["log_absences"] = (
    np.log1p(
        df_transformed["absences"]
    )
)

scaler = StandardScaler()

df_transformed["G3_standardized"] = (
    scaler.fit_transform(
        df_transformed[["G3"]]
    )
)

display(
    df_transformed[
        [
            "absences",
            "log_absences",
            "G3",
            "G3_standardized"
        ]
    ].head()
)

print("\nGROUPING DATASET")

study_group = (
    df.groupby("studytime")["G3"]
    .agg(
        [
            "count",
            "mean",
            "median",
            "std"
        ]
    )
)

print("G3 Analysis by Study Time:")
display(study_group)

gender_group = (
    df.groupby("sex")["G3"]
    .agg(
        [
            "count",
            "mean",
            "median",
            "std"
        ]
    )
)

print("\nPerformance by Gender:")
display(gender_group)

print("\nDESCRIPTIVE STATISTICS")

display(
    df[
        [
            "age",
            "Medu",
            "Fedu",
            "traveltime",
            "studytime",
            "failures",
            "famrel",
            "freetime",
            "goout",
            "Dalc",
            "Walc",
            "health",
            "absences",
            "G1",
            "G2",
            "G3"
        ]
    ].describe()
)

print("\nEDA COMPLETED SUCCESSFULLY")

DATASET LOADED SUCCESSFULLY
============================================================

DATASET SHAPE
(649, 33)

COLUMN NAMES
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

FIRST 5 ROWS

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

LAST 5 ROWS

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

DATA TYPES
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

MISSING VALUES

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Total Missing Values: 0

DUPLICATE VALUES
Number of duplicate rows: 0
No duplicate rows found.

NUMERICAL VARIABLES
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

CATEGORICAL VARIABLES
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

DATASET SLICING

First 10 rows:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13

Selected columns:

   age  studytime  failures  absences  G1  G2  G3
0   18          2         0         4   0  11  11
1   17          2         0         2   9  11  11
2   15          2         0         6  12  13  12
3   15          3         0         0  14  14  14
4   16          2         0         0  11  13  13

Students with G3 >= 15
Number of high performers: 131

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,14,15
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,6,17,17,17
31,GP,M,15,U,GT3,T,4,4,services,services,...,4,3,1,1,1,5,2,15,15,15
32,GP,M,15,R,GT3,T,4,3,teacher,at_home,...,4,5,2,1,1,5,0,13,14,15

BINARY ENCODING
Binary encoded dataset:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,0,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,0,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,0,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,0,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,0,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

ONE-HOT ENCODING
Original shape: (649, 33)
Encoded shape: (649, 42)

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,True,False,False,False,True,True,False,False
1,17,1,1,1,2,0,5,3,3,1,...,False,False,False,True,False,False,False,True,True,False
2,15,1,1,1,2,0,4,3,2,2,...,True,False,True,False,False,False,True,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,True,False,False,True,False,True,True,True,True,True
4,16,3,3,1,2,0,4,3,2,1,...,False,False,False,True,False,False,True,True,False,False

DATA TRANSFORMATION

   absences  log_absences  G3  G3_standardized
0         4      1.609438  11        -0.280658
1         2      1.098612  11        -0.280658
2         6      1.945910  12         0.029116
3         0      0.000000  14         0.648663
4         0      0.000000  13         0.338889

GROUPING DATASET
G3 Analysis by Study Time:

           count       mean  median       std
studytime
1            212  10.844340    11.0  3.218624
2            305  12.091803    12.0  3.243125
3             97  13.226804    13.0  2.502104
4             35  13.057143    13.0  3.038410

Performance by Gender:

     count       mean  median       std
sex
F      383  12.253264    12.0  3.124147
M      266  11.406015    11.0  3.320690

DESCRIPTIVE STATISTICS

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

EDA COMPLETED SUCCESSFULLY